[package]
authors = ["Jihyun Yu <yjh0502@gmail.com>"]
edition = "2018"
name = "checklfs"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
git2 = { version = "0.20.0", default-features = false, features = [] }
log = "0.4.22"
env_logger = "0.11.3"
argh = "0.1.12"
